### ISSUE TITLE
Exception has occurred: IndexError list index out of range

### ISSUE THREAD

**Issue by IvanIsak2000** [Spaceblock/Spaceblock#2]
- win10
- python 3.11.3

Is this error just me?

![image](https://user-images.githubusercontent.com/79650307/235438796-6e3a9f4c-a73c-4586-a71d-5bd01e635bf9.png)

**Comment by mb6ockatf** [comment]
> * win10
> * python 3.11.3
> 
> Is this error just me?
> 
> ![image](https://user-images.githubusercontent.com/79650307/235438796-6e3a9f4c-a73c-4586-a71d-5bd01e635bf9.png)

you should launch it with
`python3 src/app.py <some random symbols>`

these random symbols needed to handle cookies correctly, in case we'll be using them (just a good practice, otherwise flask uses it's default password - that's bad)

**Comment by IvanIsak2000** [comment]
Wow, this is really a new way to run a server!
![image](https://user-images.githubusercontent.com/79650307/235441839-5efa5528-fb2d-4174-a980-dd14b35b694d.png)

<hr>
Previously, I wrote like this, and the program could be launched by running `app.py`

![image](https://user-images.githubusercontent.com/79650307/235442013-2016cc53-f894-45a2-a170-dba90cd36832.png)

**Comment by mb6ockatf** [comment]
> Wow, this is really a new way to run a server! ![image](https://user-images.githubusercontent.com/79650307/235441839-5efa5528-fb2d-4174-a980-dd14b35b694d.png)
> 
> Previously, I wrote like this, and the program could be launched by running `app.py`
> ![image](https://user-images.githubusercontent.com/79650307/235442013-2016cc53-f894-45a2-a170-dba90cd36832.png)

@IvanIsak2000 

well, we're doing the same things. we just pass a command line parameter after `src/app.py`. it's possible to set it statically in code (although we mustn't pass it into VCS, as it's dangerous), get it as an environment variable or out of configuration file
